package com.mitrais.service;

import com.mitrais.model.AccountInfo;
import com.mitrais.model.TransferDTO;
import com.mitrais.util.DelayUtils;
import com.mitrais.util.FormatUtils;
import com.mitrais.util.Utils;

import java.util.Random;
import java.util.Scanner;
import java.util.function.Function;

public class FundTransferService implements IService {
    private AccountInfo accountInfo;
    private AccountService accountService;
    public static final String CONFIRM_OPTION = "1";

    public FundTransferService(AccountInfo accountInfo, AccountService accountService) {
        this.accountInfo = accountInfo;
        this.accountService = accountService;
    }

    @Override
    public void display() {
        Utils.clearConsole();
        System.out.println("Please enter destination account and press enter to continue or");
        System.out.print("press enter to go back to Transaction:");
    }

    @Override
    public boolean process(Scanner scanner) {
        this.display();
        TransferDTO transferDTO = getFundTransferRequest(scanner);
        if (transferDTO == null) {
            return true;
        }
        this.displayConfirmation(transferDTO);
        final String confirmationType = scanner.nextLine();
        if (CONFIRM_OPTION.equals(confirmationType)) {
            return confirmProcess(scanner, transferDTO);
        } else {
            return true;
        }
    }

    private TransferDTO getFundTransferRequest(Scanner scanner) {
        TransferDTO transferDTO = new TransferDTO();
        final String destinationAccount = scanner.nextLine();
        if (destinationAccount.length() == 0) {
            return null;
        }
        transferDTO.setDestinationNumber(destinationAccount);
        this.displayGetAmount();
        final String amount = scanner.nextLine();
        if (amount.length() == 0) {
            return null;
        }
        transferDTO.setAmount(amount);
        transferDTO.setReferenceNumber(this.displayReferenceNumber());
        scanner.nextLine();
        return transferDTO;
    }

    private boolean confirmProcess(Scanner scanner, TransferDTO transferDTO) {
        if (!this.validateUserInput(transferDTO.getDestinationNumber(), transferDTO.getAmount())) {
            DelayUtils.delay();
            return true;
        }
        AccountInfo destinationAccountInfo = transferProcess(transferDTO);
        if (destinationAccountInfo == null) return true;
        IService fundTransferSummaryService = new FundTransferSummaryService(destinationAccountInfo, Integer.valueOf(transferDTO.getAmount()), transferDTO.getReferenceNumber());
        return fundTransferSummaryService.process(scanner);
    }

    private AccountInfo transferProcess(TransferDTO transferDTO) {
        AccountInfo destinationAccountInfo = this.accountService.getUserByAccountNumber(transferDTO.getDestinationNumber());
        this.accountInfo.withdrawProcess(Integer.valueOf(transferDTO.getAmount()));
        if (this.accountInfo.getErrorMessage().length() > 0) {
            DelayUtils.delay();
            return null;
        }
        destinationAccountInfo.fundTransferProcess(Integer.valueOf(transferDTO.getAmount()));
        this.accountService.updateAccountValue(accountInfo);
        this.accountService.updateAccountValue(destinationAccountInfo);
        return destinationAccountInfo;
    }

    private void displayGetAmount() {
        Utils.clearConsole();
        System.out.println("Please enter transfer amount and");
        System.out.println("press enter to continue or");
        System.out.print("press enter to go back to Transaction:");
    }

    private int displayReferenceNumber() {
        Random random = new Random();
        int randomNumber = 100000 + random.nextInt(90000);
        Utils.clearConsole();
        System.out.println("Reference Number: " + randomNumber + "(This is an autogenerated random 6 digits number)");
        System.out.println("press enter to continue");
        return randomNumber;
    }

    private void displayConfirmation(TransferDTO transferDTO) {
        Utils.clearConsole();
        System.out.println("Transfer Confirmation");
        System.out.println("Destination Account : " + transferDTO.getDestinationNumber());
        System.out.println("Transfer Amount : $" + transferDTO.getAmount());
        System.out.println("Reference Number : " + transferDTO.getReferenceNumber());
        System.out.println("");
        System.out.println("1. Confirm Trx");
        System.out.println("2. Cancel Trx");
        System.out.print("Choose option[2]:");
    }

    private boolean validateUserInput(String destinationAccount, String amount) {
        String errorMessageValidateAccount = validateAccountFormat.apply(destinationAccount);
        if (errorMessageValidateAccount.length() > 0) {
            System.out.println(errorMessageValidateAccount);
            return false;
        }
        String errorMessageValidateAmount = validateAmountFormat.apply(amount);
        if (errorMessageValidateAmount.length() > 0) {
            System.out.println(errorMessageValidateAmount);
            return false;
        }
        return true;
    }

    private Function<String, String> validateAccountFormat = account -> {
        if (!FormatUtils.isNumeric(account)) {
            return "Invalid account";
        }
        return "";
    };

    private Function<String, String> validateAmountFormat = amountString -> {
        if (!FormatUtils.isNumeric(amountString)) {
            return "Invalid amount";
        }
        int amount = Integer.valueOf(amountString);
        final int MAX_AMOUNT_VALUE = 1000;
        final int MIN_AMOUNT_VALUE = 1;
        if (amount > MAX_AMOUNT_VALUE) {
            return "Maximum amount to withdraw is $" + MAX_AMOUNT_VALUE;
        }
        if (amount < MIN_AMOUNT_VALUE) {
            return "Minimum amount to withdraw is $" + amount;
        }
        return "";
    };
}
